### ISSUE TITLE
bench？

### ISSUE THREAD

**Issue by ncnnnnn** [nihui/ncnn-small-board#1]
up的方案是vk fp16 cpu 谁有就优先跑哪个吗

**Comment by nihui** [comment]
cpu大核心全部线程，优先fp16
vulkan是另外单独列出的，比如jetson nano

**Comment by ChungTak** [comment]
A311D (A73 2.2GHz x 4 、A53 1.8GHz x 2)    -> mobilenet: 42.57

这个4个大核为何比上面的 a55 都慢。·。·。·奇怪·~~~

**Comment by nihui** [comment]
> 

A55 启用了 fp16，A73 没有
